# Generated by Django 4.2.23 on 2025-08-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique identifier, e.g. 'hero-bg', 'footer-logo', 'team-photo-1'.", unique=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='site_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='hero/')),
                ('hero_alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
