# Generated by Django 4.2.23 on 2025-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='site_videos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
