# Generated by Django 4.2.23 on 2025-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0002_siteimage_video_sitesettings_hero_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='dev_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
