# Generated by Django 4.2.23 on 2025-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0003_devimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="The subscriber's email address.", max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text="The subscriber's name (optional).", max_length=255)),
                ('company', models.CharField(blank=True, help_text="The subscriber's company (optional).", max_length=255)),
                ('consent', models.BooleanField(default=False, help_text='Indicates if the user has consented to be contacted.')),
                ('mailchimp_status', models.CharField(default='queued', help_text="The subscriber's status in Mailchimp (e.g., queued, pending, subscribed, error:404).", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]