name: Python runtime upgrade reminder

on:
  schedule:
    - cron: '0 9 1 * *'
  workflow_dispatch:

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create or reopen reminder issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = 'Review Python runtime upgrade plan';
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            const exists = issues.find(issue => issue.title === issueTitle);
            if (!exists) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: 'Python 3.8 EOL is October 2024. Revisit the plan to upgrade to Python 3.12.',
              });
            }
